#! /bin/tcsh
if ($#argv == 1) then
	rm -f FeData.h
    echo "/* File FeData.h" > FeData.h
    echo "Auto-generated by makeFeData.sh. Do not edit. */" >> FeData.h
    echo "static const std::string gFeatureData = " >> FeData.h
	sed 's/.*/"& "/' $argv[1] >> FeData.h
	echo ";" >> FeData.h
	echo To use these weights, copy FeData.h into fuego/features
else
	echo makeFeData.sh Needs one argument: name of model file
endif
